[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["lib", "node_modules"]
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./contracts" }]

[rpc_endpoints]
base = "https://mainnet.base.org"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
